import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";

export async function GET() {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const business = await prisma.business.findFirst({ where: { userId: session.user.id } });
  if (!business) return NextResponse.json({ error: "No business found" }, { status: 404 });

  const keywords = await prisma.keyword.findMany({
    where: { businessId: business.id, isActive: true },
    include: {
      rankings: {
        orderBy: { checkedAt: "desc" },
        take: 2,
      },
    },
    orderBy: { createdAt: "asc" },
  });

  const result = keywords.map((kw) => {
    const latest = kw.rankings[0];
    const previous = kw.rankings[1];
    const change = latest && previous
      ? (previous.mapsRank ?? 999) - (latest.mapsRank ?? 999)
      : null;
    return {
      id: kw.id,
      keyword: kw.keyword,
      isAutoGenerated: kw.isAutoGenerated,
      mapsRank: latest?.mapsRank ?? null,
      organicRank: latest?.organicRank ?? null,
      change,
      checkedAt: latest?.checkedAt ?? null,
      competitorAbove: latest?.competitorAbove ?? null,
    };
  });

  return NextResponse.json({ keywords: result });
}
