import { NextResponse } from "next/server";
import { auth } from "@/auth";
import { prisma } from "@/lib/prisma";
import { z } from "zod";

const schema = z.object({ keyword: z.string().min(2).max(200) });

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user?.id) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const business = await prisma.business.findFirst({ where: { userId: session.user.id } });
  if (!business) return NextResponse.json({ error: "No business found" }, { status: 404 });

  const body = await req.json() as unknown;
  const parsed = schema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: "Invalid input" }, { status: 400 });

  const count = await prisma.keyword.count({ where: { businessId: business.id, isActive: true } });
  if (count >= 50) return NextResponse.json({ error: "Maximum 50 keywords allowed" }, { status: 400 });

  const keyword = await prisma.keyword.create({
    data: {
      businessId: business.id,
      keyword: parsed.data.keyword.toLowerCase().trim(),
      isAutoGenerated: false,
    },
  });

  return NextResponse.json({ keyword }, { status: 201 });
}
