import { Job } from "bullmq";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { getGBPAccounts } from "@/lib/gbp";

interface AuditResult {
  score: number;
  issues: string[];
  hasPhotos: boolean;
  hasHours: boolean;
  hasDescription: boolean;
  hasWebsite: boolean;
  reviewCount: number;
  avgRating: number;
}

export async function processOnboardingAudit(job: Job) {
  const { businessId } = job.data as { businessId: string };
  const start = Date.now();

  try {
    const business = await prisma.business.findUnique({
      where: { id: businessId },
      include: { googleConnection: true },
    });

    if (!business?.googleConnection) {
      throw new Error("No Google connection found");
    }

    // Fetch GBP account data
    let score = 0;
    const issues: string[] = [];
    const results: AuditResult = {
      score: 0,
      issues: [],
      hasPhotos: false,
      hasHours: false,
      hasDescription: false,
      hasWebsite: !!business.websiteUrl,
      reviewCount: 0,
      avgRating: 0,
    };

    try {
      const accounts = await getGBPAccounts(businessId);
      if (accounts?.accounts?.length > 0) {
        score += 20;
      }
    } catch {
      issues.push("Could not fetch Google Business Profile data");
    }

    if (business.websiteUrl) score += 20;
    else issues.push("No website URL set");

    if (business.phone) score += 15;
    else issues.push("No phone number set");

    if (business.addressLine1) score += 15;
    else issues.push("No address set");

    if (business.category) score += 15;
    else issues.push("No business category set");

    if (business.nicheTags?.length > 0) score += 15;
    else issues.push("No service tags set — add your main services");

    results.score = score;
    results.issues = issues;

    // Generate initial keywords
    if (business.city && business.category) {
      const baseKeywords = [
        `${business.category} ${business.city}`,
        `${business.category} near me`,
        `best ${business.category} ${business.city}`,
        `${business.category} in ${business.city}`,
        `${business.category} ${business.state ?? business.city}`,
      ];

      const nicheKeywords = (business.nicheTags ?? []).map(
        (tag) => `${tag} ${business.city}`
      );

      const allKeywords = Array.from(new Set([...baseKeywords, ...nicheKeywords])).slice(0, 20);

      // Only add if none exist yet
      const existing = await prisma.keyword.count({ where: { businessId } });
      if (existing === 0) {
        await prisma.keyword.createMany({
          data: allKeywords.map((kw) => ({
            businessId,
            keyword: kw,
            isAutoGenerated: true,
          })),
        });
      }
    }

    // Seed citations (top 50 directories)
    const directories = await prisma.citationDirectory.findMany({
      where: { isActive: true, priority: 1 },
      take: 50,
    });

    for (const dir of directories) {
      const exists = await prisma.citation.findFirst({
        where: { businessId, directoryId: dir.id },
      });
      if (!exists) {
        await prisma.citation.create({
          data: { businessId, directoryId: dir.id, status: "pending" },
        });
      }
    }

    // Create default bot settings
    await prisma.botSettings.upsert({
      where: { businessId },
      create: { businessId },
      update: {},
    });

    await prisma.business.update({
      where: { id: businessId },
      data: { onboardingComplete: true },
    });

    await logAudit({
      businessId,
      jobType: "onboarding.audit",
      status: "success",
      details: { score, issues, keywordsCreated: true },
      durationMs: Date.now() - start,
    });

    return results;
  } catch (err) {
    await logAudit({
      businessId,
      jobType: "onboarding.audit",
      status: "failed",
      details: { error: String(err) },
      durationMs: Date.now() - start,
    });
    throw err;
  }
}
